Bubble sort project in Ruby for Microverse
fedgut/mv-ruby-01-bubble pull request #1
Opened 2019-10-03 17:59 UTC by ferreirati

Bubble sort project in Ruby for Microverse

2019-10-04 21:00 UTC, Oghenebrume50 requested changes
Hi Team, good job. :+1:  I left a comment below please check that out. Since you built the other function around bubble_sort, that couldn't be tested. Please make changes and submit for a re-review :pray:

2019-10-04 21:00 UTC, Oghenebrume50 commented on src/bubble_sort.rb
> +    end
bubble_Sort function should just sort in descending order, it should not be passed a block.

2019-10-07 18:27 UTC, samgaco requested changes
Hi  @ferreirati and @fedgut :high_brightness: 

Great readme file :+1: 

- [ ] You have not implemented bubble_sort_by in your project, please address that and submit back for another code review. 


----------------
* ###### STATUS OF THE PROJECT: REQUESTED CHANGES :stop_sign:

2019-10-07 18:27 UTC, samgaco commented on src/bubble_sort.rb
> +
> Now create a similar method called #bubble_sort_by which sorts an array by accepting a block

There should be another function called **bubble_sort_by** in your project

2019-10-08 00:31 UTC, bolah2009 approved these changes
## Nice job implementing all suggested changes.

### It's a :+1: from me,

You can merge to master.

2019-10-08 17:18 UTC, merged